# Generated by Django 4.2.14 on 2024-08-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
