# Generated by Django 4.2.14 on 2024-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='salary_per_hour',
            field=models.FloatField(blank=True, default=100000, null=True),
        ),
    ]
