# Generated by Django 4.2.14 on 2024-08-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="count",
            field=models.IntegerField(default=0, help_text="Number of otp sent"),
        ),
        migrations.AddField(
            model_name="user",
            name="logged",
            field=models.BooleanField(
                default=False, help_text="If otp verification got successful"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
