# Generated by Django 4.2.14 on 2024-08-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_count_user_logged_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
