# Generated by Django 4.2.14 on 2024-07-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_national_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nurseprofile",
            old_name="Nurse_id",
            new_name="nurse_id",
        ),
    ]
