# Generated by Django 4.2.14 on 2024-08-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('mode', models.CharField(choices=[('+', 'پرداخت'), ('-', 'تسویه')], default='+', max_length=32)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.nurseprofile')),
            ],
        ),
    ]
