# Generated by Django 4.2.14 on 2024-08-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_request', '0006_request_payment_alter_request_status'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nurse_reqeust',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarnsaction', to='nurse_request.request'),
        ),
    ]
