# Generated by Django 4.2.14 on 2024-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
