# Generated by Django 4.2.14 on 2024-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_request_latitude_request_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
