# Generated by Django 4.2.14 on 2024-08-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_request_latitude_request_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="other_person_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="other_person_phone_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
