# Generated by Django 4.2.14 on 2024-08-04 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0003_request_other_person_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="request",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="request",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="request",
            name="other_person_name",
        ),
        migrations.RemoveField(
            model_name="request",
            name="other_person_phone_number",
        ),
        migrations.AddField(
            model_name="request",
            name="category",
            field=models.CharField(
                choices=[("CHILD", "فرزند خردسال"), ("ELDERLY", "والدین کهنسال")],
                default="CHILD",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="duration_hours",
            field=models.FloatField(
                default=1.0,
                help_text="مدت زمان درخواست به ساعت",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "در انتظار"),
                    ("ACCEPTED", "پذیرفته شده"),
                    ("REJECTED", "رد شده"),
                    ("COMPLETED", "تکمیل شده"),
                    ("CANCELLED", "لغو شده"),
                    ("NURSING", "پرستاری در حال انجام"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
