# Generated by Django 4.2.14 on 2024-08-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_for_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_start',
            field=models.DateTimeField(null=True),
        ),
    ]
