# Generated by Django 4.2.14 on 2024-08-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_alter_request_request_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_for_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_start',
            field=models.DateTimeField(),
        ),
    ]
