# Generated by Django 4.2.14 on 2024-08-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_request', '0002_alter_request_request_for_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
