# Generated by Django 4.2.14 on 2024-08-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_request', '0005_alter_request_status_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('ACCEPTED', 'پذیرفته شده'), ('REJECTED', 'رد شده'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده'), ('PAYMENT', 'پرداخت'), ('CLINET_CONFIRMATION', 'انتظار برای تایید متقاضی'), ('NURSING', 'پرستاری در حال انجام')], default='PENDING', max_length=20),
        ),
    ]
