# Generated by Django 4.2.14 on 2024-09-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_request', '0006_request_payment_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_end',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_for_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_start',
            field=models.CharField(blank=True, null=True),
        ),
    ]
