# Generated by Django 4.2.14 on 2024-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_request', '0007_alter_request_request_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='other_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
